version: '2.4'

services:
  db:
    image: postgres:9.4
    container_name: db
    restart: always
    tty: true
    environment: 
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=data-integration
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -t 20"]
      interval: 15s
      timeout: 5m
      retries: 5
  api:
    image: server:data-integration
    build: ./server
    container_name: api
    restart: on-failure
    ports:
      - 3000:3000
    links:
      - db
    environment:
      - DSN=host=host.docker.internal port=5432 dbname=data-integration sslmode=disable user=postgres password=root
    depends_on:
      db:
        condition: service_healthy

volumes: 
  db:
  api: